default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: gandawijaya_development
  username: cybergarage
  password: 123456

test:
  <<: *default
  database: gandawijaya_test
  username: cybergarage
  password: 123456

production:
  <<: *default
  database: gandawijaya_production
  username: gandawijaya
  password: <%= ENV['GANDAWIJAYA_DATABASE_PASSWORD'] %>
